name: ci
on:
  pull_request:
  push:
    branches:
    - main
  schedule:
  - cron: "0 1 * * *"
jobs:
  test:
    name: test
    env:
      CARGO: cargo
      # When CARGO is set to CROSS, TARGET_DIR includes matrix.target.
      TARGET_DIR: ./target
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - stable
        - beta
        - nightly
        - nightly-musl
        - nightly-arm
        - macos
        - win-msvc
        - win-gnu
        include:
        - build: stable
          os: ubuntu-24.04
          rust: stable

        - build: beta
          os: ubuntu-24.04
          rust: beta

        - build: nightly
          os: ubuntu-24.04
          rust: nightly

        - build: nightly-musl
          os: ubuntu-24.04
          rust: nightly
          target: x86_64-unknown-linux-musl

        - build: nightly-mips
          os: ubuntu-24.04
          rust: nightly
          target: mips64-unknown-linux-gnuabi64

        - build: nightly-arm
          os: ubuntu-24.04
          rust: nightly
          target: arm-unknown-linux-gnueabihf

        - build: macos
          os: macos-latest
          rust: nightly

        - build: win-msvc
          os: windows-2019
          rust: nightly

        - build: win-gnu
          os: windows-2019
          rust: nightly-x86_64-gnu
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-24.04'
      run: |
        ci/ubuntu-install-packages

    - name: Install packages (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        ci/macos-install-packages

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    - name: Use Cross
      if: matrix.target != ''
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
        echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt
    - name: Check formatting
      run: |
        cargo fmt --all -- --check

  docs:
    name: Docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --workspace
